apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: resource-management
data:
  KC_DB: oracle
  KC_DB_URL: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.eu-milan-1.oraclecloud.com))(connect_data=(service_name=g6839b910d4c8db_reservationdb_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
  KC_HOSTNAME: keycloak #TODO FIX
  KC_HTTP_PORT: "8180"
  KC_TRANSACTION_XA_ENABLED: "false"